import { NgModule } from '@angular/core';
import { NZ_ICONS, NzIconModule } from 'ng-zorro-antd/icon';

import {
  PlusCircleFill,
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FolderOpenOutline,
  FilterOutline,
  BankOutline,
  GroupOutline,
  UserOutline,
  ScheduleFill,
  HeartFill,
  EnvironmentFill,
  CrownFill,
  InstagramFill,
  SketchOutline,
  FacebookFill,
  GithubFill,
  BookFill,
  ContactsFill,
  MailFill,
  SettingOutline,
  SettingFill,
  EditFill,
  EllipsisOutline,
  PlusOutline,
  EditTwoTone,
  DeleteTwoTone,
  HeartTwoTone,
  ArrowLeftOutline,
  FormOutline,
  DeleteOutline,
  ShareAltOutline,
  DownloadOutline,
  SearchOutline,
  FilterTwoTone,
  UserAddOutline,
  DownOutline,
  PlusCircleOutline,
  HeartOutline,
  TagsFill,
  MenuOutline,
  CloseOutline,
  ExclamationCircleFill,
  ExclamationCircleOutline,
} from '@ant-design/icons-angular/icons';

const icons = [
  PlusCircleFill,
  UserOutline,
  ScheduleFill,
  HeartFill,
  EnvironmentFill,
  CrownFill,
  InstagramFill,
  SketchOutline,
  FacebookFill,
  GithubFill,
  BookFill,
  ContactsFill,
  MailFill,
  SettingFill,
  EditFill,
  EllipsisOutline,
  SettingOutline,
  PlusOutline,
  EditTwoTone,
  DeleteTwoTone,
  HeartTwoTone,
  ArrowLeftOutline,
  FormOutline,
  DeleteOutline,
  ShareAltOutline,
  DownloadOutline,
  SearchOutline,
  FilterTwoTone,
  UserAddOutline,
  DownOutline,
  PlusCircleOutline,
  HeartOutline,
  TagsFill,
  MenuOutline,
  CloseOutline,
  ExclamationCircleFill,
  ExclamationCircleOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  ArrowLeftOutline,
  UserOutline,
  DownloadOutline,
  FolderOpenOutline,
  FilterOutline,
  BankOutline,
  GroupOutline,
  UserAddOutline,
  DownOutline,
  PlusCircleOutline,
  HeartOutline,
];
@NgModule({
  imports: [NzIconModule],
  exports: [NzIconModule],
  providers: [{ provide: NZ_ICONS, useValue: icons }],
})
export class IconsProviderModule {}
